# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: æˆ‘çš„åšå®¢
subtitle: 'æ¬¢è¿å…‰ä¸´ğŸ‘ğŸ»ğŸ‘ğŸ»ğŸ‘ğŸ»ğŸ‘ğŸ»'
description: 'è®°å½•æ—¥å¸¸çš„ä¸€äº›ä¸œè¥¿'
keywords: åšå®¢
author:  Dxc123
language: zh
#ç½‘ç«™æ—¶åŒº
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://Dxc123.github.io/
#æ–‡ç« çš„ æ°¸ä¹…é“¾æ¥ æ ¼å¼
permalink: :year/:month/:day/:title/
#æ°¸ä¹…é“¾æ¥ä¸­å„éƒ¨åˆ†çš„é»˜è®¤å€¼
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
##Source æ–‡ä»¶å¤¹ å­˜å‚¨å†…å®¹çš„ä½ç½®
source_dir: source
##Public æ–‡ä»¶å¤¹ ç”Ÿæˆé™æ€ç«™ç‚¹çš„ä½ç½®
public_dir: public
##æ ‡ç­¾æ–‡ä»¶å¤¹
tag_dir: tags
##å½’æ¡£æ–‡ä»¶å¤¹
archive_dir: archives
##åˆ†ç±»æ–‡ä»¶å¤¹
category_dir: categories
##Include code æ–‡ä»¶å¤¹ï¼Œsource_dir ä¸‹çš„å­ç›®å½•
code_dir: downloads/code
##å›½é™…åŒ–ï¼ˆi18nï¼‰æ–‡ä»¶å¤¹
i18n_dir: :lang
##åŒ¹é…åˆ°çš„æ–‡ä»¶å°†ä¼šè¢«ä¸åšæ”¹åŠ¨åœ°å¤åˆ¶åˆ° public ç›®å½•ä¸­ã€‚ æ‚¨å¯ä½¿ç”¨ glob è¡¨è¾¾å¼æ¥åŒ¹é…è·¯å¾„ã€‚
skip_render:

# Writing
##æ–°æ–‡ç« çš„æ–‡ä»¶åç§°
new_post_name: :title.md # File name of new posts
#é¢„è®¾å¸ƒå±€
default_layout: post
#æŠŠæ ‡é¢˜è½¬æ¢ä¸º title case
titlecase: false # Transform title into titlecase
#åœ¨æ–°æ ‡ç­¾ä¸­æ‰“å¼€é“¾æ¥
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
#è®¾ç½®ä¸º 1 ï¼Œå°†æ–‡ä»¶åè½¬æ¢ä¸ºå°å†™å½¢å¼ï¼› è®¾ç½®ä¸º 2 ï¼Œå°†æ–‡ä»¶åè½¬æ¢ä¸ºå¤§å†™å½¢å¼ã€‚
filename_case: 0
#æ˜¾ç¤ºè‰ç¨¿
render_drafts: false
#å¯ç”¨ èµ„æºæ–‡ä»¶å¤¹
post_asset_folder: false
#æŠŠé“¾æ¥æ”¹ä¸ºä¸æ ¹ç›®å½•çš„ç›¸å¯¹ä½å€
relative_link: false
#æ˜¾ç¤ºæœªæ¥çš„æ–‡ç« 
future: true
#ä»£ç å—çš„è®¾ç½®
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
#é¦–é¡µè®¾ç½®
##ç”Ÿæˆå¸–å­å½’æ¡£ã€‚ç”± hexo-generator-index é©±åŠ¨ã€‚
index_generator:
  path: '' #åšå®¢ç´¢å¼•é¡µé¢çš„æ ¹è·¯å¾„
  per_page: 10 #æ¯é¡µæ˜¾ç¤ºå¸–å­æ•°
  order_by: -date  #å¸–å­æ’åˆ—é¡ºåºã€‚ é»˜è®¤æƒ…å†µä¸‹æŒ‰æ—¥æœŸé™åº(ä»æ–°åˆ°æ—§)ã€‚

# Category & Tag
##é»˜è®¤åˆ†ç±»  un
default_category: uncategorized
#åˆ†ç±»åˆ«å 
category_map:
#æ ‡ç­¾åˆ«å 
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
#æ—¥æœŸæ ¼å¼
date_format: YYYY-MM-DD
#æ—¶é—´æ ¼å¼
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10 #æ¯é¡µæ˜¾ç¤ºçš„å¸–å­æ•°ã€‚ 0 å…³é—­åˆ†é¡µåŠŸèƒ½ 
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
#åŒ…å«éšè—æ–‡ä»¶ï¼ˆåŒ…æ‹¬åç§°ä»¥ä¸‹åˆ’çº¿å¼€å¤´çš„æ–‡ä»¶/æ–‡ä»¶å¤¹ï¼Œ* é™¤å¤–ï¼‰
include:
#æ’é™¤æ–‡ä»¶æˆ–æ–‡ä»¶å¤¹
exclude:
#å¿½ç•¥æ–‡ä»¶/æ–‡ä»¶å¤¹
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape  #å½“å‰ä¸»é¢˜åç§°ã€‚ å€¼ä¸ºfalseæ—¶ç¦ç”¨ä¸»é¢˜
theme: cactus #https://github.com/probberechts/hexo-theme-cactus
theme_config:
  colorscheme: white
  # colorscheme: light
  # colorscheme: dark
  # colorscheme: classic

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
#éƒ¨ç½²éƒ¨åˆ†çš„è®¾ç½®
deploy:
  type: 'git'
  repository: https://github.com/Dxc123/Dxc123.github.io.git
  branch: main